name: Upload Large Files

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'رابط الملف الذي تريد رفعه'
        required: true
      custom_name:
        description: 'الاسم المخصص للملف بعد الرفع'
        required: true
      username:
        description: 'اسم المستخدم لـ Git'
        required: true
      email:
        description: 'البريد الإلكتروني لـ Git'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.event.inputs.username }}"
          git config --global user.email "${{ github.event.inputs.email }}"
          unset GITHUB_TOKEN
          gh auth login --with-token <<< "${{ secrets.GTOKEN }}"

      - name: Download large file
        run: |
          FILE_URL="${{ github.event.inputs.file_url }}"
          curl -L -o large_file "$FILE_URL"
          echo "File downloaded from $FILE_URL."

      - name: Split file into parts
        run: |
          PART_SIZE=25M
          split -b $PART_SIZE "large_file" "${{ github.event.inputs.custom_name }}_part_"
          echo "File split into parts."

      - name: Create GitHub repository
        run: |
          # إنشاء اسم مستودع يعتمد على اسم الملف مع UUID للتفرد
          FILE_NAME="${{ github.event.inputs.custom_name }}"
          UUID=$(uuidgen)
          REPO_NAME="${FILE_NAME}-${UUID}"  # مثال: myfile-123e4567-e89b-12d3-a456-426614174000
          gh repo create "$REPO_NAME" --private

      - name: Upload parts to GitHub
        run: |
          if [ -d ".git" ]; then
            echo "مستودع Git موجود بالفعل."
          else
            git init
          fi
          
          if git remote get-url origin; then
            echo "تحديث URL لـ remote origin."
            git remote set-url origin "https://github.com/your-username/$REPO_NAME.git"
          else
            echo "إضافة remote origin."
            git remote add origin "https://github.com/your-username/$REPO_NAME.git"
          fi
          
          git add "${{ github.event.inputs.custom_name }}_part_*"  # إضافة الأجزاء مع الاسم المخصص
          git commit -m "Upload split parts"
          git push -u origin master
